from __future__ import annotations

from typing import Any, Iterable, Protocol, runtime_checkable

from .graph_state import GraphEdge, GraphNode


@runtime_checkable
class GraphStateBackend(Protocol):
    nodes: dict[str, GraphNode]
    edges: dict[str, GraphEdge]
    events: list[dict[str, Any]]
    projections: dict[str, dict[str, Any]]

    def put_node(self, node_id: str, kind: str, payload: dict[str, Any]) -> None: ...
    def put_edge(self, edge_id: str, kind: str, source: str, target: str, payload: dict[str, Any]) -> None: ...
    def append_event(self, event_type: str, subject_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def put_projection(self, projection_id: str, payload: dict[str, Any]) -> None: ...
    def edges_from(self, source: str, kind: str | None = None) -> Iterable[GraphEdge]: ...
    def edges_to(self, target: str, kind: str | None = None) -> Iterable[GraphEdge]: ...
    def get_token_principal_id(self, token_node_id: str) -> str | None: ...
    def get_quota_policy_projection(self, lane: str, subject_id: str) -> dict[str, Any] | None: ...
    def replace_quota_policy_projection(self, lane: str, subject_id: str, payload: dict[str, Any]) -> None: ...
    def rebuild_quota_policy_projection(self, lane: str, subject_id: str) -> dict[str, Any]: ...
    def get_quota_used(self, lane: str, subject_id: str, period: str, when: Any | None = None) -> dict[str, float]: ...
    def add_quota_usage(self, lane: str, subject_id: str, period: str, usd: float, tokens: int, when: Any | None = None) -> None: ...
    def append_access_conversation_event(self, request_id: str, event_type: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def append_usage_ledger_event(self, lane_subject_id: str, payload: dict[str, Any]) -> str: ...


def resolve_graph_state_backend(store_kind: str, *, path: str | None = None, app_key: str | None = None, dsn: str | None = None) -> GraphStateBackend:
    if store_kind == "postgres":
        from .postgres_state import PostgresGraphStateStore

        return PostgresGraphStateStore(dsn=dsn, app_key=app_key)
    if store_kind == "kogwistar_postgres":
        from .kogwistar_postgres_state import KogwistarPostgresGraphStateStore

        return KogwistarPostgresGraphStateStore(dsn=dsn, app_key=app_key)
    from .graph_state import GraphStateStore

    return GraphStateStore(path=path, app_key=app_key)
